#!/bin/bash
# description: Foo server
#. /etc/init.d/functions
#./lib/lsb/init-functions
#. /etc/rc.d/init.d/functions
#./lib/lsb/init-functions

# Get function from functions library
#. /etc/init.d/functions
# Start the service FOO
pidfile="/var/tmp/vhs.pid"
start() {
    #initlog -c "echo -n Starting FOO server: "
   # daemon -d -v -r perl /home/nuthan/server.new 2>&1 1>/home/nuthan/logs/client1.log -l /var/log/vts.log --name=vtsdaemon --pidfiles=/var/tmp --pidfile=$pidfile 
	#daemon -d -v -r perl /home/nuthan/server.new --name=vtsdaemon 2>&1 1>/home/nuthan/logs/client1.log 
	#daemon -d -v -r perl /home/nuthan/server.new 2>&1 1>/home/nuthan/logs/client1.log --name=vtsdaemon --pidfile=$pidfile
	#daemon perl /home/nuthan/server.new -d -v -r 2>&1 1>/home/nuthan/logs/client1.log 
	perl /home/nuthan/server.new 2>&1 1>/home/nuthan/logs/client1.log &
 ### Create the lock file ###
    touch /var/lock/server1
	echo $"server1 server startup"
        echo
}
# Restart the service FOO
stop() {
    #initlog -c "echo -n Stopping server1 server: "
    if [ -f $pidfile ]; then
	PID=`cat $pidfile`
	#CPIDS=$(pgrep -P $PID); (sleep 33 && kill -KILL $CPIDS &); kill -TERM $CPIDS
	for child in `pgrep -P $PID`; do
		echo killing $child
		kill -9 $child
	done
	kill -9 $PID
	
	rm $pidfile
    fi
    ### Now, delete the lock file ###
    rm -f /var/lock/server1
    echo
}
### main logic ###
case "$1" in
start)
start
    ;;
  stop)
    stop
    ;;
 status)
    status server1
    ;;
restart|reload|condrestart)
    stop
    start
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac
exit 0
